(function(){
'use strict';
var state={kind:'download',path:'',expiry:86400,browsePath:'',shares:[],running:false};
var toastTimer=null,modalType='',confirmCallback=null,lastFocus=null;
function id(name){return document.getElementById(name)}
function el(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function toast(message,isError){var node=id('toast');node.textContent=message;node.className='toast show'+(isError?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(function(){node.className='toast'},2800)}
function request(action,data){return window.XiaomiPluginClient.request({plugin:'quickshare',cgi:'quickshare.cgi',action:action,options:{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})}}).then(function(response){return response.json().catch(function(){throw new Error('设备返回了无法解析的数据')})}).then(function(result){if(!result.ok)throw new Error(result.error||'操作失败');return result})}
function restoreFocus(){if(!lastFocus||!document.documentElement.contains(lastFocus))return;var x=window.pageXOffset,y=window.pageYOffset;try{lastFocus.focus({preventScroll:true})}catch(error){lastFocus.focus()}if(window.pageXOffset!==x||window.pageYOffset!==y)window.scrollTo(x,y)}
function openModal(type){lastFocus=document.activeElement;modalType=type;id('modalBackdrop').hidden=false;id(type).hidden=false;document.body.classList.add('modal-open')}
function closeModal(){if(!modalType)return;id(modalType).hidden=true;id('modalBackdrop').hidden=true;document.body.classList.remove('modal-open');modalType='';restoreFocus()}
function confirmAction(title,message,callback){id('confirmTitle').textContent=title;id('confirmMessage').textContent=message;confirmCallback=callback;openModal('confirmModal')}
function formatSize(bytes){var size=Number(bytes||0),units=['B','KB','MB','GB','TB'],i=0;while(size>=1024&&i<units.length-1){size/=1024;i++}return(i?size.toFixed(1):Math.round(size))+' '+units[i]}
function formatTime(value){if(!value)return'—';var date=new Date(Number(value)*1000);return date.toLocaleString()}
function statusText(value){return{active:'有效',expired:'已过期',exhausted:'次数用完',revoked:'已失效'}[value]||value}
function activatePage(page){document.querySelectorAll('.tab').forEach(function(tab){tab.classList.toggle('active',tab.dataset.page===page)});document.querySelectorAll('.page').forEach(function(node){node.classList.toggle('active',node.id==='page-'+page)});if(page==='records')loadShares();if(page==='settings')loadSettings()}

function loadStatus(showToast){return request('status').then(function(data){state.running=data.running;id('serviceBadge').className='status-pill '+(data.running?'online':'offline');id('serviceBadge').innerHTML='<i></i>'+(data.running?'服务运行中':'服务已停止');id('endpoint').textContent=data.baseUrl;id('version').textContent='插件版本 '+data.pluginVersion;id('recordSummary').textContent=data.activeShares+' 个有效 · '+data.totalShares+' 条记录';id('startService').disabled=data.running;id('stopService').disabled=!data.running;if(showToast)toast('状态已刷新')}).catch(function(error){id('serviceBadge').className='status-pill offline';id('serviceBadge').innerHTML='<i></i>连接失败';toast(error.message,true)})}
function loadSettings(){return request('settings_get').then(function(data){id('externalBase').value=data.externalBase||'';id('lanAddress').textContent='局域网地址：'+data.lanUrl}).catch(function(error){toast(error.message,true)})}
function updateKind(kind){state.kind=kind;state.path='';document.querySelectorAll('#kindSwitch button').forEach(function(button){button.classList.toggle('active',button.dataset.kind===kind)});id('targetTitle').textContent=kind==='download'?'选择文件':'选择上传文件夹';id('targetHint').textContent=kind==='download'?'只会开放选中的单个文件。':'朋友上传的文件会保存到所选文件夹。';id('selectedPath').textContent=kind==='download'?'尚未选择文件':'尚未选择文件夹';id('selectedPath').className='selected-path empty';id('usesLabel').textContent=kind==='download'?'最多下载次数':'最多上传文件数'}

function openBrowser(){state.browsePath='';id('browserTitle').textContent=state.kind==='download'?'选择文件':'选择上传文件夹';id('chooseFolder').hidden=state.kind!=='upload';openModal('browserModal');browse('')}
function parentPath(path){var parts=String(path||'').split('/').filter(Boolean);parts.pop();return parts.join('/')}
function browse(path){id('browserList').className='file-list loading';id('browserList').textContent='正在读取…';request('browse',{path:path}).then(function(data){state.browsePath=data.path||'';id('browserPath').textContent=state.browsePath||'根目录';id('browserBack').disabled=!state.browsePath;id('chooseFolder').hidden=state.kind!=='upload'||!state.browsePath;renderBrowser(data.entries||[])}).catch(function(error){id('browserList').textContent=error.message;toast(error.message,true)})}
function renderBrowser(entries){var list=id('browserList');list.textContent='';list.className='file-list';var visible=entries.filter(function(item){return item.type==='dir'||state.kind==='download'});if(!visible.length){list.className='file-list empty-state';list.textContent=state.kind==='download'?'此目录没有可分享的文件':'此目录没有子文件夹';return}visible.forEach(function(item){var button=el('button','file-row');button.type='button';button.appendChild(el('span','file-icon',item.type==='dir'?'▰':'▤'));var copy=el('span','file-copy');copy.appendChild(el('strong','',item.name));copy.appendChild(el('span','',item.type==='dir'?'文件夹':formatSize(item.size)));button.appendChild(copy);button.addEventListener('click',function(){if(item.type==='dir')browse(item.path);else selectPath(item.path)});list.appendChild(button)})}
function selectPath(path){state.path=path;id('selectedPath').textContent=path;id('selectedPath').className='selected-path';closeModal()}

function createShare(){var password=id('password').value,maxUses=Number(id('maxUses').value);if(!state.path){toast(state.kind==='download'?'请先选择文件':'请先选择上传文件夹',true);return}if(password&&password.length<4){toast('密码至少需要 4 位',true);return}if(!Number.isInteger(maxUses)||maxUses<0||maxUses>1000){toast('次数必须是 0–1000 的整数',true);return}var button=id('createButton');button.disabled=true;request('create',{kind:state.kind,path:state.path,password:password,expiresIn:state.expiry,maxUses:maxUses}).then(function(data){id('password').value='';id('createdLink').value=data.share.url;openModal('linkModal');loadStatus(false);loadShares()}).catch(function(error){toast(error.message,true)}).finally(function(){button.disabled=false})}
function copyText(value){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(value);var area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();var ok=document.execCommand('copy');document.body.removeChild(area);return ok?Promise.resolve():Promise.reject(new Error('复制失败'))}

function loadShares(){var list=id('shareList');list.className='stack loading';list.textContent='正在读取分享记录…';return request('list').then(function(data){state.shares=data.shares||[];renderShares()}).catch(function(error){list.textContent=error.message;toast(error.message,true)})}
function renderShares(){var list=id('shareList');list.textContent='';list.className='stack';if(!state.shares.length){list.className='stack empty-state';list.textContent='还没有分享记录。';return}state.shares.forEach(function(share){var card=el('article','share-card');var head=el('div','share-head'),title=el('div','share-title');title.appendChild(el('h3','',share.name));title.appendChild(el('p','',share.path));head.appendChild(title);head.appendChild(el('span','badge'+(share.status==='active'?'':' inactive'),statusText(share.status)));card.appendChild(head);var meta=el('div','share-meta');meta.appendChild(el('span','chip',share.kind==='download'?'下载分享':'上传入口'));meta.appendChild(el('span','chip',share.password_protected?'密码保护':'无密码'));meta.appendChild(el('span','chip','已使用 '+share.uses+(share.max_uses?'/'+share.max_uses:'/不限')));meta.appendChild(el('span','chip','到期 '+formatTime(share.expires_at)));if(share.last_used_at)meta.appendChild(el('span','chip','最近 '+formatTime(share.last_used_at)));card.appendChild(meta);var actions=el('div','share-actions');var copy=el('button','','复制链接');copy.type='button';copy.addEventListener('click',function(){copyText(share.url).then(function(){toast('链接已复制')}).catch(function(error){toast(error.message,true)})});actions.appendChild(copy);var open=el('a','','打开');open.href=share.url;open.target='_blank';open.rel='noreferrer';actions.appendChild(open);if(share.status==='active'){var revoke=el('button','revoke','立即失效');revoke.type='button';revoke.addEventListener('click',function(){confirmAction('使分享失效','失效后原链接将立即无法访问，是否继续？',function(){request('revoke',{id:share.id}).then(function(){toast('分享已失效');loadShares();loadStatus(false)}).catch(function(error){toast(error.message,true)})})});actions.appendChild(revoke)}card.appendChild(actions);list.appendChild(card)})}

document.querySelectorAll('.tab').forEach(function(tab){tab.addEventListener('click',function(){activatePage(tab.dataset.page)})});
document.querySelectorAll('#kindSwitch button').forEach(function(button){button.addEventListener('click',function(){updateKind(button.dataset.kind)})});
document.querySelectorAll('#expiryChoices button').forEach(function(button){button.addEventListener('click',function(){state.expiry=Number(button.dataset.value);document.querySelectorAll('#expiryChoices button').forEach(function(item){item.classList.toggle('active',item===button)})})});
id('refresh').addEventListener('click',function(){loadStatus(true);loadShares()});id('browseButton').addEventListener('click',openBrowser);id('browserBack').addEventListener('click',function(){browse(parentPath(state.browsePath))});id('chooseFolder').addEventListener('click',function(){selectPath(state.browsePath)});id('closeBrowser').addEventListener('click',closeModal);id('createButton').addEventListener('click',createShare);id('closeLink').addEventListener('click',closeModal);id('copyCreatedLink').addEventListener('click',function(){copyText(id('createdLink').value).then(function(){toast('链接已复制');closeModal()}).catch(function(error){toast(error.message,true)})});
id('modalBackdrop').addEventListener('click',function(){if(modalType==='confirmModal'){confirmCallback=null}closeModal()});id('confirmCancel').addEventListener('click',function(){confirmCallback=null;closeModal()});id('confirmAccept').addEventListener('click',function(){var callback=confirmCallback;confirmCallback=null;closeModal();if(callback)callback()});
id('saveSettings').addEventListener('click',function(){var value=id('externalBase').value.trim();if(value&&!/^https?:\/\//i.test(value)){toast('请输入完整的 HTTP 或 HTTPS 地址',true);return}var button=this;button.disabled=true;request('settings_save',{externalBase:value}).then(function(data){toast('公网分享地址已保存');id('endpoint').textContent=data.baseUrl;loadShares()}).catch(function(error){toast(error.message,true)}).finally(function(){button.disabled=false})});
id('startService').addEventListener('click',function(){var button=this;button.disabled=true;request('server_start').then(function(){toast('分享服务已启动');return loadStatus(false)}).catch(function(error){toast(error.message,true)}).finally(function(){button.disabled=false})});id('stopService').addEventListener('click',function(){confirmAction('停止分享服务','停止后所有临时链接都会暂时无法访问，但分享记录不会删除。',function(){request('server_stop').then(function(){toast('分享服务已停止');loadStatus(false)}).catch(function(error){toast(error.message,true)})})});
document.addEventListener('keydown',function(event){if(event.key==='Escape'&&modalType){if(modalType==='confirmModal')confirmCallback=null;closeModal()}});
var swipe=null;document.querySelector('.shell').addEventListener('touchstart',function(event){if(event.touches.length!==1||event.target.closest('button,input,textarea,a')||modalType){swipe=null;return}var touch=event.touches[0];if(touch.clientX<24||touch.clientX>window.innerWidth-24){swipe=null;return}swipe={x:touch.clientX,y:touch.clientY}},{passive:true});document.querySelector('.shell').addEventListener('touchend',function(event){if(!swipe||!event.changedTouches.length)return;var touch=event.changedTouches[0],dx=touch.clientX-swipe.x,dy=touch.clientY-swipe.y;swipe=null;if(Math.abs(dx)<55||Math.abs(dx)<Math.abs(dy)*1.35)return;var pages=['create','records','settings'],active=document.querySelector('.tab.active'),index=pages.indexOf(active?active.dataset.page:'create'),next=dx<0?index+1:index-1;if(next>=0&&next<pages.length)activatePage(pages[next])},{passive:true});
loadStatus(false);loadShares();loadSettings();
})();
